version: "3.3"
services:
  sqs:
    image: 288840537196.dkr.ecr.eu-west-1.amazonaws.com/tech.form3/elasticmq
    ports:
      - 1212:1212
    volumes:
      - ./sqs/queues.conf:/queues.conf
    environment:
      BIND_PORT: 1212
      NODE_HOST: sqs
  s3:
    image: form3tech/form3-s3rver
    ports:
      - 5000:5000
    volumes:
      - ./s3/s3.json:/form3-s3rver/s3.json

  sns:
    image: 288840537196.dkr.ecr.eu-west-1.amazonaws.com/tech.form3/sns
    ports:
      - 9911:9911
    depends_on:
      - sqs
    volumes:
      - ./sns/sns.json:/etc/sns/db.json.template
    environment:
      SQS_PORT: 1212
      SQS_HOST: sqs

  wait_for:
    image: dadarek/wait-for-dependencies
    depends_on:
      - sqs
      - sns
      - s3
    command: sqs:1212 sns:9911 s3:5000
